# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-19 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pacientes', models.BooleanField(default=True)),
                ('administrador', models.BooleanField(default=True)),
                ('territorios', models.BooleanField(default=True)),
                ('entidades', models.BooleanField(default=True)),
                ('personas', models.BooleanField(default=True)),
                ('salud', models.BooleanField(default=True)),
                ('gestion_entidad', models.BooleanField(default=True)),
                ('medicamento', models.BooleanField(default=True)),
                ('reporte_general', models.BooleanField(default=True)),
                ('reporte_balance', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_datos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('ubicacion', models.CharField(max_length=45, null=True)),
                ('piso', models.IntegerField(default=1)),
                ('extension', models.IntegerField(default=1)),
                ('estado', models.CharField(max_length=45, null=True)),
                ('publico', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('dependencias', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Dependencias')),
                ('perfiles', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Perfiles')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
