# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20220207_1612'),
        ('interlocutorc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_datos',
            name='perfiles',
        ),
        migrations.AddField(
            model_name='usuarios_datos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas'),
        ),
    ]
