# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-26 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0003_historiausuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios_datos',
            old_name='publico',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='usuarios_datos',
            old_name='cedula',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='usuarios_datos',
            old_name='estado',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuarios_datos',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='usuarios_datos',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='usuarios_datos',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuarios_datos',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='usuarios_datos',
            name='ubicacion',
        ),
    ]
