# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0004_auto_20220426_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialErrorTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
