# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0005_auto_20220602_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialerrortarea',
            name='empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialerrortarea',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='historialerrortarea',
            name='pedido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialerrortarea',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
