# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0006_auto_20220801_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios_datos',
            name='atencion',
            field=models.IntegerField(default=1),
        ),
    ]
