# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0007_usuarios_datos_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEmpresa', models.CharField(max_length=100, null=True)),
                ('Identificacion', models.CharField(max_length=100, null=True)),
                ('TipoIdentificacion', models.CharField(max_length=100, null=True)),
                ('Correo', models.CharField(max_length=100, null=True)),
                ('ValorOrden', models.CharField(max_length=100, null=True)),
                ('FechaEntrega', models.DateField(null=True)),
                ('FechaPago', models.DateField(null=True)),
                ('FechaHoy', models.DateField(null=True)),
                ('NumeroPedido', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialErrorApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, null=True)),
                ('pedido', models.CharField(max_length=100, null=True)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
            ],
        ),
    ]
