# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0008_clientesapi_historialerrorapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEmpresa', models.CharField(max_length=100, null=True)),
                ('Identificacion', models.CharField(max_length=100, null=True)),
                ('TipoIdentificacion', models.CharField(max_length=100, null=True)),
                ('Correo', models.CharField(max_length=100, null=True)),
                ('ValorOrden', models.CharField(max_length=100, null=True)),
                ('FechaPago', models.DateField(null=True)),
                ('FechaHoy', models.DateField(null=True)),
                ('NumeroPedido', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
