# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-09 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0009_facturasapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaOrdenCompraApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identificacion', models.CharField(max_length=100, null=True)),
                ('TipoIdentificacion', models.CharField(max_length=100, null=True)),
                ('ValorAprobado', models.CharField(max_length=100, null=True)),
                ('FechaEmision', models.DateField(null=True)),
                ('NumeroOrdenCompra', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
