# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0010_respuestaordencompraapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaFacturaApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identificacion', models.CharField(max_length=100, null=True)),
                ('TipoIdentificacion', models.CharField(max_length=100, null=True)),
                ('ValorAprobado', models.CharField(max_length=100, null=True)),
                ('FechaEmision', models.DateField(null=True)),
                ('NumeroFactura', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='facturasapi',
            old_name='FechaPago',
            new_name='FechaPagoFactura',
        ),
        migrations.RenameField(
            model_name='facturasapi',
            old_name='NumeroPedido',
            new_name='NumeroFactura',
        ),
        migrations.RenameField(
            model_name='facturasapi',
            old_name='ValorOrden',
            new_name='ValorFacturaEmitida',
        ),
    ]
