# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-16 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0011_auto_20230214_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEmailEnviados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100, null=True)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
            ],
        ),
    ]
