# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0012_historialemailenviados'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestafacturaapi',
            name='Impuesto',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='respuestaordencompraapi',
            name='Impuesto',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
