# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0013_auto_20230220_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestafacturaapi',
            old_name='Impuesto',
            new_name='Interes',
        ),
        migrations.RenameField(
            model_name='respuestaordencompraapi',
            old_name='Impuesto',
            new_name='Interes',
        ),
    ]
