# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-22 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0014_auto_20230221_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialemailenviados',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialemailenviados',
            name='tipo',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
