# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-10 02:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0015_auto_20230221_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestafacturaapi',
            name='FechaEmision',
            field=models.DateField(default=datetime.date(1, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='respuestafacturaapi',
            name='Identificacion',
            field=models.CharField(default='0000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestafacturaapi',
            name='Interes',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestafacturaapi',
            name='NumeroFactura',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestafacturaapi',
            name='TipoIdentificacion',
            field=models.CharField(default='NIT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestafacturaapi',
            name='ValorAprobado',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaordencompraapi',
            name='FechaEmision',
            field=models.DateField(default=datetime.date(1, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='respuestaordencompraapi',
            name='Identificacion',
            field=models.CharField(default='0000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaordencompraapi',
            name='Interes',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaordencompraapi',
            name='NumeroOrdenCompra',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaordencompraapi',
            name='TipoIdentificacion',
            field=models.CharField(default='NIT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaordencompraapi',
            name='ValorAprobado',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
