# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0016_auto_20230309_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasApis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEmpresa', models.CharField(max_length=100, null=True)),
                ('Identificacion', models.CharField(max_length=100, null=True)),
                ('TipoIdentificacion', models.CharField(max_length=100, null=True)),
                ('Correo', models.CharField(max_length=100, null=True)),
                ('ValorFacturaEmitida', models.CharField(max_length=100, null=True)),
                ('FechaPagoFactura', models.DateField(null=True)),
                ('FechaHoy', models.DateField(null=True)),
                ('NumeroFactura', models.CharField(max_length=100, null=True)),
                ('Referencia2', models.CharField(default='0', max_length=100, null=True)),
            ],
        ),
    ]
