# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-26 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0017_facturasapis'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasapi',
            name='Referencia2',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
