# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0018_facturasapi_referencia2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEmailReEnviados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100, null=True)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('tipo', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
