# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0019_historialemailreenviados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graficas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tipo_usuario', models.CharField(default=None, max_length=45)),
                ('grafico', models.CharField(max_length=100)),
                ('tabla', models.CharField(default='', max_length=100, null=True)),
                ('campo', models.CharField(default='', max_length=100, null=True)),
                ('area', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles_PCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('comercial', models.BooleanField(default=True)),
                ('exportaciones', models.BooleanField(default=True)),
                ('desarrollo_empresarial', models.BooleanField(default=True)),
                ('administrativo_financiero', models.BooleanField(default=True)),
                ('mercadeo_innovacion', models.BooleanField(default=True)),
                ('operaciones_logistica', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios_datos',
            name='pcs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios_datos',
            name='perfil_pcs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interlocutorc.Perfiles_PCS'),
        ),
    ]
