# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-16 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0021_auto_20230614_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficas',
            name='nivel',
            field=models.IntegerField(default=10),
        ),
    ]
