# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-23 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0022_graficas_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles_pcs',
            name='analista_senior_2',
            field=models.BooleanField(default=False),
        ),
    ]
