# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0023_perfiles_pcs_analista_senior_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios_datos',
            name='estado_sistema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interlocutorc.EstadoSistema'),
        ),
    ]
