# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-18 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0024_auto_20230628_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaEstadoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, null=True)),
                ('razon', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interlocutorc.Usuarios_datos')),
            ],
        ),
    ]
