# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-23 01:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0019_auto_20231221_2113'),
        ('interlocutorc', '0025_historiaestadosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrediListoPreaprobado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoIdentificacion', models.CharField(default='NIT', max_length=100, null=True)),
                ('ValorAprobado', models.CharField(default='0', max_length=100, null=True)),
                ('NumeroFactura', models.CharField(default='0', max_length=100, null=True)),
                ('NumeroFacturaCliente', models.CharField(default='0', max_length=100, null=True)),
                ('Interes', models.CharField(default='0', max_length=100, null=True)),
                ('estado', models.CharField(default=None, max_length=100, null=True)),
                ('FechaEmision', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('FechaVencimiento', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('FechaSolicitud', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('ValorFactura', models.CharField(default=None, max_length=100, null=True)),
                ('Correo', models.CharField(default=None, max_length=100, null=True)),
                ('FechaRespuesta', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('Razon', models.CharField(default=None, max_length=500, null=True)),
                ('Empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas')),
                ('UsuarioRespuesta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrediyaPreaprobado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoIdentificacion', models.CharField(default='NIT', max_length=100, null=True)),
                ('ValorAprobado', models.CharField(default='0', max_length=100, null=True)),
                ('NumeroOrdenCompra', models.CharField(default='0', max_length=100, null=True)),
                ('Interes', models.CharField(default='0', max_length=100, null=True)),
                ('estado', models.CharField(default=None, max_length=100, null=True)),
                ('FechaEmision', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('FechaVencimiento', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('FechaSolicitud', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('ValorOrden', models.CharField(default=None, max_length=100, null=True)),
                ('Correo', models.CharField(default=None, max_length=100, null=True)),
                ('FechaRespuesta', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('Razon', models.CharField(default=None, max_length=500, null=True)),
                ('Empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas')),
                ('UsuarioRespuesta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagare', models.CharField(default=None, max_length=100, null=True)),
                ('contrato', models.CharField(default=None, max_length=100, null=True)),
                ('carta', models.CharField(default=None, max_length=100, null=True)),
                ('ficha', models.CharField(default=None, max_length=100, null=True)),
                ('estado', models.CharField(default=None, max_length=100, null=True)),
                ('FechaEmision', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('Correo', models.CharField(default=None, max_length=100, null=True)),
                ('Razon', models.CharField(default=None, max_length=500, null=True)),
                ('Empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDocumentosCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagare', models.CharField(default=None, max_length=100, null=True)),
                ('contrato', models.CharField(default=None, max_length=100, null=True)),
                ('carta', models.CharField(default=None, max_length=100, null=True)),
                ('ficha', models.CharField(default=None, max_length=100, null=True)),
                ('estado', models.CharField(default=None, max_length=100, null=True)),
                ('FechaRespuesta', models.DateField(default=datetime.date(1, 1, 1), null=True)),
                ('Razon', models.CharField(default=None, max_length=500, null=True)),
                ('UsuarioRespuesta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interlocutorc.DocumentosCredito')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaOrdenCompraApis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEmpresa', models.CharField(max_length=255)),
                ('Identificacion', models.CharField(max_length=255)),
                ('TipoIdentificacion', models.CharField(max_length=255)),
                ('ReferenciaOrdenes', models.CharField(max_length=255)),
                ('ValorAprobado', models.CharField(max_length=255)),
                ('FechaEmision', models.DateField(blank=True, null=True)),
                ('Interes', models.CharField(max_length=255)),
                ('NumeroOrdenCompra', models.CharField(max_length=255)),
                ('Estado', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
