# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-12 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0026_credilistopreaprobado_crediyapreaprobado_documentoscredito_historialdocumentoscredito_respuestaorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialErrorEnvioSap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, null=True)),
                ('pedido', models.CharField(max_length=100, null=True)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('mensaje_sistema', models.CharField(max_length=500, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historialerrorapi',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
