# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-03 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0027_auto_20240411_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosRegistros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('creado', models.DateTimeField(null=True)),
                ('asignado', models.DateTimeField(null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios_datos',
            name='codigoregistro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='interlocutorc.CodigosRegistros'),
        ),
    ]
