# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-12 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0028_auto_20240702_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosregistros',
            name='codigo_cliente',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
