# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-26 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interlocutorc', '0030_loginattempt_loginattemptdjango'),
    ]

    operations = [
        migrations.AddField(
            model_name='credilistopreaprobado',
            name='UsuarioSolicitado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudescredilisto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crediyapreaprobado',
            name='Almacen',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crediyapreaprobado',
            name='UsuarioSolicitado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credilistopreaprobado',
            name='UsuarioRespuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestascredilisto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crediyapreaprobado',
            name='UsuarioRespuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL),
        ),
    ]
