# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0031_auto_20240725_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='credilistopreaprobado',
            name='EgresoCreado',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crediyapreaprobado',
            name='EgresoCreado',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
