# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-05 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0032_auto_20241125_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='credilistopreaprobado',
            name='Interes_aplicado',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credilistopreaprobado',
            name='ValorAprobado_aplicado',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
