# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-23 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0033_auto_20250304_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='credilistopreaprobado',
            name='CrucesAplicados',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
