# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-21 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0028_pedidosotroscanales_fecha_entrega'),
        ('interlocutorc', '0034_credilistopreaprobado_crucesaplicados'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaDetallePedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, null=True)),
                ('pedido', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('estado', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interlocutorc.Usuarios_datos')),
            ],
        ),
    ]
