# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-19 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atorizaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarpetaAno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, null=True)),
                ('ano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Anos')),
            ],
        ),
        migrations.CreateModel(
            name='Consecutivos',
            fields=[
                ('codigo', models.CharField(default=1, max_length=200, primary_key=True, serialize=False)),
                ('ano', models.IntegerField(null=True)),
                ('secuencia', models.CharField(max_length=6, null=True)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('tipo', models.CharField(default=1, max_length=50)),
                ('accion', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('codigo', models.CharField(default=1, max_length=8, primary_key=True, serialize=False)),
                ('codigopadre', models.CharField(max_length=8)),
                ('codigoterritorio', models.CharField(max_length=8)),
                ('sigla', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('continentes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Continentes')),
                ('departamentos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Dependencias_visibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencias', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Dependencias')),
            ],
        ),
        migrations.CreateModel(
            name='Estantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fechas_festivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formas_envios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fe', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('genera_planilla', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soporte', models.CharField(max_length=30)),
                ('estado', models.CharField(default='activo', max_length=30)),
                ('dependencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Dependencias')),
            ],
        ),
        migrations.CreateModel(
            name='Medios_recepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=45)),
                ('departamentos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='NivelEstantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('estante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Estantes')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=45)),
                ('continentes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Continentes')),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('registrar_localizacion', models.BooleanField(default=False)),
                ('editar_localizacion', models.BooleanField(default=False)),
                ('borrar_localizacion', models.BooleanField(default=False)),
                ('consultar_localizacion', models.BooleanField(default=False)),
                ('registrar_anulaciones', models.BooleanField(default=False)),
                ('editar_anulaciones', models.BooleanField(default=False)),
                ('borrar_anulaciones', models.BooleanField(default=False)),
                ('consultar_anulaciones', models.BooleanField(default=False)),
                ('registrar_tipo_radicado', models.BooleanField(default=False)),
                ('editar_tipo_radicado', models.BooleanField(default=False)),
                ('borrar_tipo_radicado', models.BooleanField(default=False)),
                ('consultar_tipo_radicado', models.BooleanField(default=False)),
                ('registrar_tipo_envio', models.BooleanField(default=False)),
                ('editar_tipo_envio', models.BooleanField(default=False)),
                ('borrar_tipo_envio', models.BooleanField(default=False)),
                ('consultar_tipo_envio', models.BooleanField(default=False)),
                ('registrar_formas_envio', models.BooleanField(default=False)),
                ('editar_formas_envio', models.BooleanField(default=False)),
                ('borrar_formas_envio', models.BooleanField(default=False)),
                ('consultar_formas_envio', models.BooleanField(default=False)),
                ('registrar_soportes', models.BooleanField(default=False)),
                ('editar_soportes', models.BooleanField(default=False)),
                ('borrar_soportes', models.BooleanField(default=False)),
                ('consultar_soportes', models.BooleanField(default=False)),
                ('registrar_medios', models.BooleanField(default=False)),
                ('editar_medios', models.BooleanField(default=False)),
                ('borrar_medios', models.BooleanField(default=False)),
                ('consultar_medios', models.BooleanField(default=False)),
                ('registrar_motivos_dev', models.BooleanField(default=False)),
                ('editar_motivos_dev', models.BooleanField(default=False)),
                ('borrar_motivos_dev', models.BooleanField(default=False)),
                ('consultar_motivos_dev', models.BooleanField(default=False)),
                ('registrar_terceros', models.BooleanField(default=False)),
                ('editar_terceros', models.BooleanField(default=False)),
                ('borrar_terceros', models.BooleanField(default=False)),
                ('consultar_terceros', models.BooleanField(default=False)),
                ('registrar_series', models.BooleanField(default=False)),
                ('editar_series', models.BooleanField(default=False)),
                ('borrar_series', models.BooleanField(default=False)),
                ('consultar_series', models.BooleanField(default=False)),
                ('registrar_subseries', models.BooleanField(default=False)),
                ('editar_subseries', models.BooleanField(default=False)),
                ('borrar_subseries', models.BooleanField(default=False)),
                ('consultar_subseries', models.BooleanField(default=False)),
                ('registrar_tipos_documentos', models.BooleanField(default=False)),
                ('editar_tipos_documentos', models.BooleanField(default=False)),
                ('borrar_tipos_documentos', models.BooleanField(default=False)),
                ('consultar_tipos_documentos', models.BooleanField(default=False)),
                ('registrar_usuarios', models.BooleanField(default=False)),
                ('editar_usuarios', models.BooleanField(default=False)),
                ('borrar_usuarios', models.BooleanField(default=False)),
                ('consultar_usuarios', models.BooleanField(default=False)),
                ('registrar_fechas_festivos', models.BooleanField(default=False)),
                ('editar_fechas_festivos', models.BooleanField(default=False)),
                ('borrar_fechas_festivos', models.BooleanField(default=False)),
                ('consultar_fechas_festivos', models.BooleanField(default=False)),
                ('registrar_dependencias', models.BooleanField(default=False)),
                ('editar_dependencias', models.BooleanField(default=False)),
                ('borrar_dependencias', models.BooleanField(default=False)),
                ('consultar_dependencias', models.BooleanField(default=False)),
                ('registrar_facturas_compra', models.BooleanField(default=False)),
                ('editar_facturas_compra', models.BooleanField(default=False)),
                ('borrar_facturas_compra', models.BooleanField(default=False)),
                ('consultar_facturas_compra', models.BooleanField(default=False)),
                ('registrar_entradas', models.BooleanField(default=False)),
                ('editar_entradas', models.BooleanField(default=False)),
                ('borrar_entradas', models.BooleanField(default=False)),
                ('consultar_entradas', models.BooleanField(default=False)),
                ('registrar_salidas', models.BooleanField(default=False)),
                ('editar_salidas', models.BooleanField(default=False)),
                ('borrar_salidas', models.BooleanField(default=False)),
                ('consultar_salidas', models.BooleanField(default=False)),
                ('registrar_internos', models.BooleanField(default=False)),
                ('editar_internos', models.BooleanField(default=False)),
                ('borrar_internos', models.BooleanField(default=False)),
                ('consultar_internos', models.BooleanField(default=False)),
                ('registrar_admin_anulacion', models.BooleanField(default=False)),
                ('editar_admin_anulacion', models.BooleanField(default=False)),
                ('borrar_admin_anulacion', models.BooleanField(default=False)),
                ('consultar_admin_anulacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.CharField(max_length=50)),
                ('piso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Piso')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=600)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=20)),
                ('proceso', models.CharField(max_length=30)),
                ('procedimiento', models.CharField(max_length=30)),
                ('soporte', models.CharField(default=1, max_length=30)),
                ('retencionag', models.IntegerField(null=True)),
                ('retencionac', models.IntegerField(null=True)),
                ('dispocicion_final', models.CharField(default=1, max_length=30)),
                ('observacion', models.CharField(max_length=600)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=45, null=True)),
                ('telefono', models.CharField(max_length=9999999999999L, null=True)),
                ('telefono2', models.CharField(max_length=9999999999999L, null=True)),
                ('celular', models.IntegerField(null=True)),
                ('nit', models.IntegerField(null=True)),
                ('dv', models.CharField(max_length=9, null=True)),
                ('representante_legal', models.CharField(max_length=45, null=True)),
                ('tipo_tercero', models.CharField(max_length=2, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('continentes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Continentes')),
                ('departamentos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Departamentos')),
                ('municipios', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Municipios')),
                ('paises', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Paises')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_anulaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_devoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('dias_tramite', models.IntegerField(null=True)),
                ('publicar', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('dependencias', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Dependencias')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_envios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_radicados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tr', models.CharField(max_length=20)),
                ('genera_radicado_salida', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('version', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=20)),
                ('acta', models.CharField(max_length=40)),
                ('fechaaprobacion', models.DateField(null=True)),
                ('observacion', models.CharField(max_length=600)),
                ('creado', models.DateTimeField(null=True)),
                ('modificado', models.DateTimeField(null=True)),
                ('administrativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrativa', to='configuracion.Dependencias')),
                ('productora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productora', to='configuracion.Dependencias')),
                ('series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Series')),
                ('subseries', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Subseries')),
            ],
        ),
        migrations.CreateModel(
            name='Trd_tiposdocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('trd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Trd')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('continentes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Continentes')),
                ('departamentos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Departamentos')),
                ('municipios', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Municipios')),
                ('paises', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Paises')),
            ],
        ),
        migrations.AddField(
            model_name='tipos_documentos',
            name='tipos_radicados',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Tipos_radicados'),
        ),
        migrations.AddField(
            model_name='salones',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Ubicacion'),
        ),
        migrations.AddField(
            model_name='piso',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Ubicacion'),
        ),
        migrations.AddField(
            model_name='nivelestantes',
            name='piso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Piso'),
        ),
        migrations.AddField(
            model_name='nivelestantes',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Salones'),
        ),
        migrations.AddField(
            model_name='nivelestantes',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Ubicacion'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Series'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='subserie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Subseries'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='tipos_documentos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Tipos_documentos'),
        ),
        migrations.AddField(
            model_name='formas_envios',
            name='tipos_envios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Tipos_envios'),
        ),
        migrations.AddField(
            model_name='estantes',
            name='piso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Piso'),
        ),
        migrations.AddField(
            model_name='estantes',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Salones'),
        ),
        migrations.AddField(
            model_name='estantes',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Ubicacion'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='municipios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Municipios'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='paises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Paises'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='paises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Paises'),
        ),
        migrations.AddField(
            model_name='consecutivos',
            name='dependencias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Dependencias'),
        ),
        migrations.AddField(
            model_name='consecutivos',
            name='usuario_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpetaano',
            name='dependencias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Dependencias'),
        ),
        migrations.AddField(
            model_name='carpetaano',
            name='usuario_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atorizaciones',
            name='opciones',
            field=models.ManyToManyField(to='configuracion.Opciones'),
        ),
        migrations.AddField(
            model_name='atorizaciones',
            name='perfiles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Perfiles'),
        ),
    ]
