# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('movil', models.CharField(max_length=30)),
                ('responsable', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='atorizaciones',
            name='perfiles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas'),
        ),
    ]
