# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0002_auto_20220207_1612'),
        ('configuracion', '0002_auto_20220207_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfiles',
        ),
        migrations.AddField(
            model_name='empresas',
            name='continentes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Continentes'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='departamentos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Departamentos'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='municipios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Municipios'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='paises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Paises'),
        ),
    ]
