# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-26 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interlocutorc', '0004_auto_20220426_0928'),
        ('configuracion', '0003_auto_20220207_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpetaano',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='carpetaano',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='carpetaano',
            name='usuario_origen',
        ),
        migrations.RemoveField(
            model_name='consecutivos',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='consecutivos',
            name='usuario_origen',
        ),
        migrations.RemoveField(
            model_name='dependencias',
            name='continentes',
        ),
        migrations.RemoveField(
            model_name='dependencias',
            name='departamentos',
        ),
        migrations.RemoveField(
            model_name='dependencias',
            name='municipios',
        ),
        migrations.RemoveField(
            model_name='dependencias',
            name='paises',
        ),
        migrations.RemoveField(
            model_name='dependencias_visibles',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='subserie',
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='tipos_documentos',
        ),
        migrations.RemoveField(
            model_name='tipos_documentos',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='tipos_documentos',
            name='tipos_radicados',
        ),
        migrations.RemoveField(
            model_name='trd',
            name='administrativa',
        ),
        migrations.RemoveField(
            model_name='trd',
            name='productora',
        ),
        migrations.RemoveField(
            model_name='trd',
            name='series',
        ),
        migrations.RemoveField(
            model_name='trd',
            name='subseries',
        ),
        migrations.RemoveField(
            model_name='trd_tiposdocumentos',
            name='trd',
        ),
        migrations.DeleteModel(
            name='Anos',
        ),
        migrations.DeleteModel(
            name='CarpetaAno',
        ),
        migrations.DeleteModel(
            name='Consecutivos',
        ),
        migrations.DeleteModel(
            name='Dependencias',
        ),
        migrations.DeleteModel(
            name='Dependencias_visibles',
        ),
        migrations.DeleteModel(
            name='Matriz',
        ),
        migrations.DeleteModel(
            name='Tipos_documentos',
        ),
        migrations.DeleteModel(
            name='Trd',
        ),
        migrations.DeleteModel(
            name='Trd_tiposdocumentos',
        ),
    ]
