# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20220426_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosAlmacenados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=40)),
            ],
        ),
    ]
