# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_pedidosalmacenados'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PersonasAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.AreasAtencion')),
            ],
        ),
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.AreasAtencion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pedido', models.CharField(max_length=80)),
                ('entry_pedido', models.CharField(max_length=80)),
                ('adicionales', models.CharField(max_length=80)),
                ('fecha', models.DateField(null=True)),
                ('estado', models.CharField(default=None, max_length=80, null=True)),
                ('respuesta', models.CharField(default=None, max_length=80, null=True)),
                ('peticion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Peticiones')),
            ],
        ),
    ]
