# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_areasatencion_personasatencion_peticiones_respuestapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapedido',
            name='empresa',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
