# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_respuestapedido_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='personasatencion',
            name='usuario',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='personasatencion',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
