# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20220919_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapedido',
            name='doc_respuesta',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
