# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-05 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_respuestapedido_doc_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='respuestapedido',
            name='adicionales',
        ),
        migrations.AddField(
            model_name='respuestapedido',
            name='email',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='respuestapedido',
            name='justificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Justificacion'),
        ),
    ]
