# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_auto_20221005_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosNovedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cantidad', models.CharField(max_length=20)),
                ('modificado', models.CharField(default='no', max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('peticion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.RespuestaPedido')),
            ],
        ),
    ]
