# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_pedidosnovedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.CharField(max_length=20)),
                ('cajas', models.CharField(max_length=20)),
                ('vehiculo', models.CharField(max_length=20)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('peticion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.RespuestaPedido')),
            ],
        ),
    ]
