# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_respuestacita'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestacita',
            name='orden_compra',
            field=models.CharField(default='1', max_length=80),
        ),
        migrations.AddField(
            model_name='respuestapedido',
            name='hora',
            field=models.TimeField(default='01:01:00', null=True),
        ),
    ]
