# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0013_auto_20221028_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapedido',
            name='justificacion_adicional',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
