# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0014_respuestapedido_justificacion_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRespuestaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pedido', models.CharField(max_length=80)),
                ('empresa', models.CharField(default=None, max_length=80, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(default='01:01:00', null=True)),
                ('email', models.CharField(default=None, max_length=80, null=True)),
                ('accion', models.CharField(default=None, max_length=100, null=True)),
                ('peticion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Peticiones')),
            ],
        ),
    ]
