# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-10 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0015_logrespuestapedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graficas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tipo_usuario', models.CharField(default=None, max_length=45)),
                ('grafico', models.CharField(max_length=100)),
            ],
        ),
    ]
