# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-03 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0016_graficas'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficas',
            name='campo',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graficas',
            name='tabla',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
