# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-17 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_auto_20230403_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graficas',
        ),
    ]
