# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_delete_graficas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPedidosOtrosCanales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesPedidosOtrosCanales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('referencia', models.CharField(max_length=50)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('observaciones', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesOtrosCanales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidosOtrosCanales',
            fields=[
                ('num_pedido', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(default='01:01:00', null=True)),
                ('estado', models.CharField(default='en proceso', max_length=80, null=True)),
                ('fecha_minima', models.DateField(null=True)),
                ('fecha_maxima', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='edi',
            field=models.CharField(default='1', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pedidosotroscanales',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas'),
        ),
        migrations.AddField(
            model_name='detallespedidosotroscanales',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas'),
        ),
        migrations.AddField(
            model_name='detallespedidosotroscanales',
            name='num_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.PedidosOtrosCanales'),
        ),
        migrations.AddField(
            model_name='asignacionpedidosotroscanales',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresas'),
        ),
        migrations.AddField(
            model_name='asignacionpedidosotroscanales',
            name='num_detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.DetallesPedidosOtrosCanales'),
        ),
    ]
