# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-10 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_auto_20231221_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='temporada',
            field=models.BooleanField(default=False),
        ),
    ]
