# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0020_empresas_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='cliente',
            field=models.BooleanField(default=False),
        ),
    ]
