# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-15 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0022_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpedidosotroscanales',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='codigo',
            field=models.CharField(default='1', max_length=30, null=True),
        ),
    ]
