# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-28 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0023_auto_20240814_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosotroscanales',
            name='numero_pedido_cliente',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
