# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-10-17 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0024_pedidosotroscanales_numero_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenesotroscanales',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
