# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0025_imagenesotroscanales_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('u_pedidas', models.CharField(max_length=50)),
                ('cant_un_ped', models.CharField(max_length=50)),
                ('unidades_despachar', models.CharField(max_length=50)),
                ('empaques_despachado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empaque', models.CharField(max_length=150)),
                ('tipo_embalaje', models.CharField(max_length=150)),
                ('entry', models.CharField(max_length=150)),
                ('pedido', models.CharField(default=1, max_length=150)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(default='01:01:00', null=True)),
                ('estado', models.CharField(default='activo', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='detalleordenventa',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.OrdenVenta'),
        ),
    ]
