# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-24 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0026_auto_20241125_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordenventa',
            name='dependencia',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detalleordenventa',
            name='direccion',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detalleordenventa',
            name='plu',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detalleordenventa',
            name='tota_bruto',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detalleordenventa',
            name='total_neto',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='doc_edi',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='doc_respuesta',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='factura',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
