# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-18 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0027_auto_20241224_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosotroscanales',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
    ]
