# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-27 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0028_pedidosotroscanales_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpedidosotroscanales',
            name='cantidadfacturada',
            field=models.IntegerField(default=0),
        ),
    ]
