# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0029_asignacionpedidosotroscanales_cantidadfacturada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpedidosotroscanales',
            name='cantidadrecibo',
            field=models.IntegerField(default=0),
        ),
    ]
